import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HoverToolbar from "@/components/HoverToolbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "This Website Does Not Exist",
    description: "Every page is uniquely generated by AI",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <HoverToolbar />
            </body>
        </html>
    );
}
