import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HoverToolbar from "@/components/HoverToolbar";
import { GenerationStatsProvider } from "@/contexts/GenerationStatsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "This Website Does Not Exist",
    description: "Every page is uniquely generated by AI",
    viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <GenerationStatsProvider>
                    {children}
                    <HoverToolbar />
                </GenerationStatsProvider>
            </body>
        </html>
    );
}
