"use client";

import { useState, useEffect } from "react";
import { useRouter, usePathname } from "next/navigation";
import { motion, AnimatePresence, Variants } from "framer-motion";
import { generateRandomPath } from "@/lib/randomPaths";
import { useGenerationStats } from "@/contexts/GenerationStatsContext";
import Tooltip from "./Tooltip";
import MotionToolButton from "./MotionToolButton";
import SocialIcon from "./SocialIcon";
import Icon from "./Icon";

const container: Variants = {
    hidden: {
        opacity: 0,
        transition: { staggerChildren: 0.05, staggerDirection: -1 },
    },
    show: {
        opacity: 1,
        transition: {
            staggerChildren: 0.05,
            delayChildren: 0.05,
        },
    },
};

const item: Variants = {
    hidden: {
        opacity: 0,
        y: 10,
        transition: { duration: 0.2 },
    },
    show: {
        opacity: 1,
        y: 0,
        transition: {
            type: "spring",
            stiffness: 500,
            damping: 25,
        },
    },
};

export default function HoverToolbar() {
    const { generationStats } = useGenerationStats();
    const router = useRouter();
    const pathname = usePathname();
    const [isExpanded, setIsExpanded] = useState(true);
    const [history, setHistory] = useState<string[]>([]);
    const [isRegenerating, setIsRegenerating] = useState(false);
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        const checkMobile = () => {
            setIsMobile(window.innerWidth <= 768);
        };

        checkMobile();
        window.addEventListener("resize", checkMobile);

        setTimeout(() => {
            setIsExpanded(false);
        }, 2000);

        return () => window.removeEventListener("resize", checkMobile);
    }, []);

    // Load history on mount and save new paths
    useEffect(() => {
        // Load history from localStorage
        const savedHistory = localStorage.getItem("pathHistory");
        if (savedHistory) {
            setHistory(JSON.parse(savedHistory));
        }

        // Add current path to history if it's not the latest
        if (pathname !== "/") {
            setHistory((prev) => {
                const newHistory = [
                    pathname,
                    ...prev.filter((path) => path !== pathname),
                ].slice(0, 100); // Keep MAX_HISTORY logic
                localStorage.setItem("pathHistory", JSON.stringify(newHistory));
                return newHistory;
            });
        }
    }, [pathname]);

    const handleSoftReload = async () => {
        try {
            setIsRegenerating(true);
            const iframe = document.querySelector("iframe");
            if (iframe?.contentDocument) {
                const currentHTML =
                    iframe.contentDocument.documentElement.outerHTML;
                iframe.contentDocument.open();
                iframe.contentDocument.write(currentHTML);
                iframe.contentDocument.close();
            }
        } catch (error) {
            console.error("Error during soft reload:", error);
        } finally {
            setIsRegenerating(false);
        }
    };

    const handleRandomClick = () => {
        const randomPath = generateRandomPath();
        router.push(randomPath);
    };

    const handleDownload = () => {
        // Get the iframe element
        const iframe = document.querySelector("iframe");
        if (!iframe?.contentDocument) return;

        // Get the HTML content
        const html = iframe.contentDocument.documentElement.outerHTML;

        // Create a blob and download link
        const blob = new Blob([html], { type: "text/html" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${pathname.slice(1) || "home"}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleShare = () => {
        const text = `Check out this AI-generated website I found: ${pathname}\n\nGenerated by This Website Does Not Exist 🤖✨\n`;
        const url = typeof window !== "undefined" ? window.location.href : "";
        window.open(
            `https://twitter.com/intent/tweet?text=${encodeURIComponent(
                text
            )}&url=${encodeURIComponent(url)}`,
            "_blank"
        );
    };

    return (
        <div className="relative">
            {/* Mobile peek-out button */}
            {isMobile && !isExpanded && (
                <motion.button
                    className="fixed top-4 right-0 z-[9999] bg-black/40 backdrop-blur-xl text-white p-2 rounded-l-xl shadow-lg ring-1 ring-white/20"
                    onClick={() => setIsExpanded(true)}
                    initial={{ x: 0 }}
                    animate={{ x: 0 }}
                    whileHover={{ x: -5 }}
                    whileTap={{ scale: 0.95 }}
                >
                    <Icon type="sparkles" className="w-6 h-6" />
                </motion.button>
            )}

            {/* Desktop hover area */}
            {!isMobile && (
                <div
                    className="fixed top-0 right-0 w-24 h-screen z-[9998] bg-transparent"
                    onMouseEnter={() => setIsExpanded(true)}
                />
            )}

            <AnimatePresence>
                {(!isMobile || isExpanded) && (
                    <motion.div
                        className="fixed top-4 right-4 z-[9999] h-[calc(100vh-2rem)]"
                        initial={
                            isMobile ? { x: "100%" } : { width: "4rem", x: 10 }
                        }
                        animate={{
                            width: isExpanded
                                ? isMobile
                                    ? "calc(100vw - 2rem)"
                                    : "20rem"
                                : "4rem",
                            x: isExpanded ? 0 : isMobile ? "100%" : 10,
                        }}
                        exit={isMobile ? { x: "100%" } : undefined}
                        transition={{
                            duration: 0.2,
                            ease: [0.2, 0, 0, 1],
                        }}
                        onMouseLeave={() => !isMobile && setIsExpanded(false)}
                    >
                        <motion.div
                            className="bg-black/40 backdrop-blur-2xl text-white h-full relative rounded-2xl ring-1 ring-white/20 overflow-hidden"
                            animate={{
                                scale: isExpanded ? 1 : 0.98,
                            }}
                            transition={{ duration: 0.2 }}
                        >
                            {/* Close button for mobile */}
                            {isMobile && (
                                <motion.button
                                    className="absolute top-2 right-2 z-10 p-2 rounded-lg bg-black/20 hover:bg-black/40 transition-colors"
                                    onClick={() => setIsExpanded(false)}
                                    initial={{ opacity: 0, scale: 0.8 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0, scale: 0.8 }}
                                >
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        className="w-6 h-6"
                                        fill="none"
                                        viewBox="0 0 24 24"
                                        stroke="currentColor"
                                    >
                                        <path
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                            strokeWidth={2}
                                            d="M6 18L18 6M6 6l12 12"
                                        />
                                    </svg>
                                </motion.button>
                            )}

                            <div className="absolute inset-0 bg-gradient-to-b from-white/[0.08] to-transparent pointer-events-none rounded-2xl" />
                            <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/20 to-black/40 pointer-events-none rounded-2xl" />

                            {/* Rest of the existing toolbar content */}
                            <AnimatePresence mode="wait">
                                {isExpanded ? (
                                    <motion.div
                                        key="expanded"
                                        className="absolute inset-0 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:none]"
                                        initial="hidden"
                                        animate="show"
                                        exit="hidden"
                                        variants={container}
                                    >
                                        <div className="p-6 min-h-full flex flex-col gap-3 relative">
                                            <div className="flex-none">
                                                <motion.h2
                                                    variants={item}
                                                    className="text-md font-bold mb-1 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent tracking-tight"
                                                >
                                                    Tools
                                                </motion.h2>

                                                <motion.div
                                                    variants={container}
                                                    className="space-y-2"
                                                >
                                                    <motion.div
                                                        variants={item}
                                                        className="bg-black/20 backdrop-blur rounded-xl p-2 space-y-1 ring-1 ring-white/10"
                                                    >
                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="refresh" />
                                                            }
                                                            text="Hard Reload"
                                                            tooltip="Regenerate with new content"
                                                            onClick={() =>
                                                                window.location.reload()
                                                            }
                                                        />

                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="sparkles" />
                                                            }
                                                            text="Soft Reload"
                                                            tooltip="Refresh the current content"
                                                            onClick={
                                                                handleSoftReload
                                                            }
                                                            isLoading={
                                                                isRegenerating
                                                            }
                                                            disabled={
                                                                isRegenerating
                                                            }
                                                        />
                                                    </motion.div>

                                                    <motion.div
                                                        variants={item}
                                                        className="bg-black/20 backdrop-blur rounded-xl p-2 space-y-1 ring-1 ring-white/10"
                                                    >
                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="dice" />
                                                            }
                                                            text="Random"
                                                            tooltip="Generate random website"
                                                            onClick={
                                                                handleRandomClick
                                                            }
                                                        />

                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="download" />
                                                            }
                                                            text="Download HTML"
                                                            tooltip="Download page HTML"
                                                            onClick={
                                                                handleDownload
                                                            }
                                                        />

                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="share" />
                                                            }
                                                            text="Share on Twitter"
                                                            tooltip="Share this website on Twitter"
                                                            onClick={
                                                                handleShare
                                                            }
                                                        />

                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="home" />
                                                            }
                                                            text="Home"
                                                            tooltip="Return to home page"
                                                            onClick={() =>
                                                                router.push("/")
                                                            }
                                                        />

                                                        <MotionToolButton
                                                            icon={
                                                                <Icon type="analytics" />
                                                            }
                                                            text="Searchboard"
                                                            tooltip="View search analytics"
                                                            onClick={() =>
                                                                router.push(
                                                                    "/searchboard"
                                                                )
                                                            }
                                                        />
                                                    </motion.div>
                                                </motion.div>
                                            </div>

                                            <motion.div
                                                variants={item}
                                                className="flex-none"
                                            >
                                                <div className="text-sm">
                                                    <motion.div
                                                        variants={item}
                                                        className="font-medium mb-1 text-white/90"
                                                    >
                                                        Current Path
                                                    </motion.div>
                                                    <motion.div
                                                        variants={item}
                                                        className="bg-black/20 backdrop-blur rounded-xl p-3 font-mono text-sm break-all shadow-[inset_0_2px_4px_rgba(0,0,0,0.1)] ring-1 ring-white/10"
                                                    >
                                                        <div className="truncate">
                                                            {pathname}
                                                        </div>
                                                    </motion.div>
                                                </div>
                                            </motion.div>

                                            {generationStats &&
                                                pathname !== "/" &&
                                                pathname !== "/searchboard" && (
                                                    <motion.div
                                                        variants={item}
                                                        className="flex-none"
                                                    >
                                                        <div className="text-sm">
                                                            <motion.div
                                                                variants={item}
                                                                className="font-medium mb-1 text-white/90"
                                                            >
                                                                Generation Stats
                                                            </motion.div>
                                                            <motion.div
                                                                variants={item}
                                                                className="bg-black/20 backdrop-blur rounded-xl p-3 shadow-[inset_0_2px_4px_rgba(0,0,0,0.1)] ring-1 ring-white/10 cursor-pointer hover:bg-black/30 transition-colors"
                                                                onClick={() =>
                                                                    window.open(
                                                                        "/searchboard",
                                                                        "_blank"
                                                                    )
                                                                }
                                                                whileHover={{
                                                                    scale: 1.02,
                                                                }}
                                                                whileTap={{
                                                                    scale: 0.98,
                                                                }}
                                                            >
                                                                <div className="space-y-2 text-xs">
                                                                    <div className="flex items-center justify-between">
                                                                        <span className="text-white/70">
                                                                            Total
                                                                            sites:
                                                                        </span>
                                                                        <span className="font-mono bg-white/10 px-2 py-0.5 rounded text-blue-300">
                                                                            {
                                                                                generationStats.totalSiteGenerations
                                                                            }{" "}
                                                                            time
                                                                            {generationStats.totalSiteGenerations !==
                                                                            1
                                                                                ? "s"
                                                                                : ""}
                                                                        </span>
                                                                    </div>
                                                                    <div className="flex items-center justify-between">
                                                                        <span className="text-white/70">
                                                                            This
                                                                            path:
                                                                        </span>
                                                                        <span className="font-mono bg-white/10 px-2 py-0.5 rounded text-purple-300">
                                                                            {
                                                                                generationStats.pathGenerations
                                                                            }{" "}
                                                                            time
                                                                            {generationStats.pathGenerations !==
                                                                            1
                                                                                ? "s"
                                                                                : ""}
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </motion.div>
                                                        </div>
                                                    </motion.div>
                                                )}

                                            {history.length > 0 && (
                                                <motion.div
                                                    variants={item}
                                                    className="text-sm flex-none"
                                                >
                                                    <motion.div
                                                        variants={item}
                                                        className="font-medium mb-1 flex items-center justify-between text-white/90"
                                                    >
                                                        <span className="truncate">
                                                            History
                                                        </span>
                                                        <div className="flex gap-1 flex-none ml-2">
                                                            <Tooltip text="Scroll up">
                                                                <motion.button
                                                                    variants={
                                                                        item
                                                                    }
                                                                    onClick={() => {
                                                                        const container =
                                                                            document.querySelector(
                                                                                "#history-container"
                                                                            );
                                                                        if (
                                                                            container
                                                                        ) {
                                                                            container.scrollBy(
                                                                                {
                                                                                    top: -41,
                                                                                    behavior:
                                                                                        "smooth",
                                                                                }
                                                                            );
                                                                        }
                                                                    }}
                                                                    className="w-8 h-6 flex items-center justify-center bg-black/20 hover:bg-black/40 rounded-lg transition-all duration-150 text-white/90 hover:text-white hover:scale-110 active:scale-95 ring-1 ring-white/10"
                                                                    whileHover={{
                                                                        scale: 1.1,
                                                                    }}
                                                                    whileTap={{
                                                                        scale: 0.95,
                                                                    }}
                                                                >
                                                                    ▲
                                                                </motion.button>
                                                            </Tooltip>
                                                            <Tooltip text="Scroll down">
                                                                <motion.button
                                                                    variants={
                                                                        item
                                                                    }
                                                                    onClick={() => {
                                                                        const container =
                                                                            document.querySelector(
                                                                                "#history-container"
                                                                            );
                                                                        if (
                                                                            container
                                                                        ) {
                                                                            container.scrollBy(
                                                                                {
                                                                                    top: 41,
                                                                                    behavior:
                                                                                        "smooth",
                                                                                }
                                                                            );
                                                                        }
                                                                    }}
                                                                    className="w-8 h-6 flex items-center justify-center bg-black/20 hover:bg-black/40 rounded-lg transition-all duration-150 text-white/90 hover:text-white hover:scale-110 active:scale-95 ring-1 ring-white/10 cursor-pointer"
                                                                    whileHover={{
                                                                        scale: 1.1,
                                                                    }}
                                                                    whileTap={{
                                                                        scale: 0.95,
                                                                    }}
                                                                >
                                                                    ▼
                                                                </motion.button>
                                                            </Tooltip>
                                                        </div>
                                                    </motion.div>
                                                    <motion.div
                                                        variants={item}
                                                        className="h-40 bg-black/20 backdrop-blur rounded-xl shadow-[inset_0_2px_4px_rgba(0,0,0,0.1)] ring-1 ring-white/10"
                                                    >
                                                        <div
                                                            id="history-container"
                                                            className="h-full overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:'none'] [scrollbar-width:none] p-2"
                                                        >
                                                            <motion.div
                                                                variants={
                                                                    container
                                                                }
                                                                className="space-y-1"
                                                            >
                                                                {history.map(
                                                                    (
                                                                        path,
                                                                        index
                                                                    ) => (
                                                                        <motion.a
                                                                            key={
                                                                                index
                                                                            }
                                                                            variants={
                                                                                item
                                                                            }
                                                                            onClick={(
                                                                                e
                                                                            ) => {
                                                                                e.preventDefault();
                                                                                router.push(
                                                                                    path
                                                                                );
                                                                            }}
                                                                            className="block px-3 py-2 bg-black/20 hover:bg-black/40 rounded-lg font-mono text-sm transition-all duration-150 cursor-pointer hover:scale-[1.02] active:scale-[0.98] ring-1 ring-white/10"
                                                                            whileHover={{
                                                                                scale: 1.02,
                                                                            }}
                                                                            whileTap={{
                                                                                scale: 0.98,
                                                                            }}
                                                                        >
                                                                            <div className="truncate">
                                                                                {
                                                                                    path
                                                                                }
                                                                            </div>
                                                                        </motion.a>
                                                                    )
                                                                )}
                                                            </motion.div>
                                                        </div>
                                                    </motion.div>
                                                </motion.div>
                                            )}

                                            <motion.div
                                                variants={item}
                                                className="sticky bottom-4 w-full bg-white/50 backdrop-blur-md rounded-xl p-2 ring-1 ring-white/10"
                                            >
                                                <div className="grid grid-cols-2 gap-2">
                                                    <MotionToolButton
                                                        icon={
                                                            <SocialIcon
                                                                type="github"
                                                                className="w-5 h-5"
                                                            />
                                                        }
                                                        text="GitHub"
                                                        tooltip="Visit my GitHub profile"
                                                        onClick={() =>
                                                            window.open(
                                                                "https://github.com/itsmarsss/thiswebsitedoesnotexist",
                                                                "_blank"
                                                            )
                                                        }
                                                    />
                                                    <MotionToolButton
                                                        icon={
                                                            <SocialIcon
                                                                type="x"
                                                                className="w-5 h-5"
                                                            />
                                                        }
                                                        text="X"
                                                        tooltip="Visit my X profile"
                                                        onClick={() =>
                                                            window.open(
                                                                "https://x.com/__kennywu__",
                                                                "_blank"
                                                            )
                                                        }
                                                    />
                                                </div>
                                            </motion.div>
                                        </div>
                                    </motion.div>
                                ) : (
                                    !isMobile && (
                                        <motion.div
                                            key="collapsed"
                                            className="absolute inset-0 flex items-center justify-center bg-gradient-to-b from-white/[0.08] via-transparent to-transparent"
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            exit={{ opacity: 0 }}
                                            transition={{ duration: 0.15 }}
                                        >
                                            <motion.div
                                                className="rotate-90 whitespace-nowrap text-sm text-white/90 tracking-wider font-medium"
                                                initial={{ opacity: 0, y: 10 }}
                                                animate={{ opacity: 1, y: 0 }}
                                                exit={{ opacity: 0, y: 10 }}
                                                transition={{
                                                    type: "spring",
                                                    stiffness: 500,
                                                    damping: 25,
                                                }}
                                            >
                                                Hover for tools
                                            </motion.div>
                                        </motion.div>
                                    )
                                )}
                            </AnimatePresence>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
